### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by chienhuak**
郭千華：
Stage 2 Task 2 - Render index.html
http://13.54.113.48:8000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Layout width should not exceed screen width in any size of devices.
- Take attention on every detail: color, border, alignment

**Comment by chienhuak** [comment]
郭千華：
Part 2 : index page
--> 修正畫面超出螢幕問題
--> 對齊 "搜尋框"、"MRT按鈕"、"圖片" 
--> 調整邊框樣式 "搜尋框"、"圖片"
http://13.54.113.48:8000/

Part 3 : attraction page
http://13.54.113.48:8000/
http://13.54.113.48:8000/attraction/10

Part 4 : sign in/up/out interface
http://13.54.113.48:8000
http://13.54.113.48:8000/api/user/auth

**Review by cwpeng — CHANGES_REQUESTED** [review]
Part 2 is OK.

For part 3:

- Size of arrow buttons is too large, we should always align with design in Figma.
- More details: color and padding.
13 54 113 48_8000_attraction_15

For part 4:

After you fixed part 3, you should merge pull request first, and create another pull request for part 4 review. You should follow the working flow.

**Comment by chienhuak** [comment]
Part 3 : attraction page
--> adjust arrow buttons size
--> adjust radio buttons style
--> adjust text style
--> modify date default not selected
http://13.54.113.48:8000/
http://13.54.113.48:8000/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
Border and padding of date input element should align with design.
13 54 113 48_8000_attraction_3

**Comment by chienhuak** [comment]
> Border and padding of date input element should align with design. 13 54 113 48_8000_attraction_3

What I fixed :
--> adjust date input element's padding & border

Questions : 
--> should I handle the date format difference in different device?
--> should I make the calendar icon as same as figma?

image

image

image

**Review by cwpeng — APPROVED** [review]
Part 3 is OK. Merge this pull request and create another pull request for another part.

**Pull request merged**
