### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by chienhuak**
郭千華
Part 5 : booking page
http://13.54.113.48:8000/
http://13.54.113.48:8000/attraction/10
http://13.54.113.48:8000/booking

NOTE : 
- The api is not totally same as original api instruction, but it's because I tried to make it able to add more than 1 booking items to the shopping cart.
image

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout details in the booking page: color, border, padding, alignment.

**Comment by chienhuak** [comment]
> Layout details in the booking page: color, border, padding, alignment.

--> It's updated.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Padding of input elements should align with design.

**Comment by chienhuak** [comment]
> Padding of input elements should align with design.

--> Updated the input elements style to align with Figma.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
